server/apps/main/urls.py
from django.urls import path, re_path
from server.apps.main import views
from server.apps.main import feeds

app_name = "main"

urlpatterns = [
    re_path(r"^$", views.index, name="index"),
    re_path(r"^signup/?$", views.signup, name="signup"),
    re_path(r"^login/?$", views.login_user, name="login"),
    re_path(r"^logout/?$", views.logout_user, name="logout"),
    re_path(
        r"^public_experiences/?$",
        views.list_public_experiences,
        name="public_experiences",
    ),
    re_path(
        r"^moderate_public_experiences/?$",
        views.moderate_public_experiences,
        name="moderate_public_experiences",
    ),
    re_path(r"moderation_list/?$", views.moderation_list, name="moderation_list"),
    path("delete/<uuid>/", views.delete_experience, name="delete_exp"),
    path("share_exp/", views.share_experience, name="share_exp"),
    path("edit/<uuid>/", views.share_experience, name="edit_exp"),
    path("moderate/<uuid>/", views.moderate_experience, name="moderate_exp"),
    path("view/<uuid>/", views.view_experience, name="view_exp"),
    path("my_stories/", views.my_stories, name="my_stories"),
    path("about_us/", views.about_us, name="about_us"),
    path("what_autism_is/", views.what_autism_is, name="what_autism_is"),
    path("help/", views.help, name="help"),
    path("content_moderation_guidelines/", views.content_moderation_guidelines, name="content_moderation_guidelines"),
    path("participant_information/", views.participant_information, name="participant_information"),
    path("registration/", views.registration, name="registration"),
    path("single_story/<uuid>/",views.single_story,name="single_story"),
    path("success_confirm/", views.success_confirm, name="success_confirm"),
    path("public_experiences/rss.xml", feeds.PublicExperienceFeed(), name='rss_feed'),
    path("public_experiences/atom.xml", feeds.PublicExperienceAtomFeed(), name='atom_feed'),
]

server/apps/users/urls.py
from django.urls import path, re_path
from server.apps.users import views

app_name = "servers.apps.users"

urlpatterns = [
    path("profile/", views.user_profile, name="profile"),
    path("greetings/", views.user_profile, {"first_visit": True}, name="greetings"),
    path("delete/", views.user_profile_delete, name="delete"),
]

server/urls.py
"""
Main URL mapping configuration file.

Include other URLConfs from external apps using method `include()`.

It is also a good practice to keep a single URL to the root index page.

This examples uses Django's default media
files serving technique in development.
"""

from django.conf import settings
from django.contrib import admin
from django.contrib.admindocs import urls as admindocs_urls
from django.urls import include, path
from django.views.generic import TemplateView
from health_check import urls as health_urls

from server.apps.main import urls as main_urls
from server.apps.main.views import index
from server.apps.users import urls as users_urls

admin.autodiscover()

urlpatterns = [
    # Apps:
    path('main/', include(main_urls, namespace='main')),
    path('users/', include(users_urls, namespace='users')),

    # Health checks:
    path('health/', include(health_urls)),  # noqa: DJ05

    # django-admin:
    path('admin/doc/', include(admindocs_urls)),  # noqa: DJ05
    path('admin/', admin.site.urls),

    # Text and xml static files:
    path('robots.txt', TemplateView.as_view(
        template_name='txt/robots.txt',
        content_type='text/plain',
    )),
    path('humans.txt', TemplateView.as_view(
        template_name='txt/humans.txt',
        content_type='text/plain',
    )),

    # It is a good practice to have explicit index view:
    path('', index, name='index'),
]

# Appending url patterns for the prototype
urlpatterns += [
    path('openhumans/', include('openhumans.urls')),
]

if settings.DEBUG:  # pragma: no cover
    import debug_toolbar  # noqa: WPS433
    from django.conf.urls.static import static  # noqa: WPS433

    urlpatterns = [
        # URLs specific only to django-debug-toolbar:
        path('__debug__/', include(debug_toolbar.urls)),  # noqa: DJ05
    ] + urlpatterns + static(  # type: ignore
        # Serving media files in development only:
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

server/apps/main/models.py
from django.db import models
from openhumans.models import OpenHumansMember


class PublicExperience(models.Model):
    experience_text = models.TextField()
    difference_text = models.TextField(default="")
    title_text = models.TextField(default="")
    created_at = models.DateTimeField(auto_now=True)
    experience_id = models.TextField(primary_key=True) #if specified as primary key you cannot have duplicates.
    open_humans_member = models.ForeignKey(OpenHumansMember,
                                           blank=True, null=True,
                                           on_delete=models.CASCADE)
    moderation_status = models.CharField(
        blank=False,
        default='not reviewed',
        max_length=50)
    
    abuse = models.BooleanField(default=False)
    violence = models.BooleanField(default=False)
    drug = models.BooleanField(default=False)
    mentalhealth = models.BooleanField(default=False)
    negbody = models.BooleanField(default=False)
    other = models.TextField(default="")
    
    research = models.BooleanField(default=False)

    authorship_choices = ((False, "Experience is someone else's"), (True, "Experience is my own"))
    first_hand_authorship = models.BooleanField(choices=authorship_choices, default=False)
    authorship_relation = models.TextField(default="")

    def __str__(self):
        return self.experience_text

class ExperienceHistory(models.Model):
    experience = models.ForeignKey(PublicExperience, on_delete=models.CASCADE)
    change_type = models.TextField()
    changed_at = models.DateTimeField(auto_now=True)
    changed_by = models.ForeignKey(OpenHumansMember, 
                                   blank=False,
                                   null=False,
                                   on_delete=models.CASCADE)
    change_comments = models.TextField(default="")
    change_reply = models.TextField(default="")

    def __str__(self):
        return self.change_type

server/apps/main/views.py
import io
import json
import logging
import vcr

import requests
from django.conf import settings
from django.contrib.auth import logout
from django.shortcuts import redirect, render
from openhumans.models import OpenHumansMember
from django.db.models import Q
from django.urls import reverse
from django.core.paginator import Paginator
from django.core.exceptions import ObjectDoesNotExist
from django.forms.models import model_to_dict

from .models import PublicExperience, ExperienceHistory
from server.apps.users.models import UserProfile

from .forms import ShareExperienceForm, ModerateExperienceForm

from django.contrib import messages

from server.apps.main.helpers import (
    is_moderator,
    public_experience_model_to_form,
    extract_experience_details,
    reformat_date_string,
    get_review_status,
    get_oh_combined,
    delete_single_file_and_pe,
    upload,
    rebuild_experience_data,
    make_uuid,
    delete_PE,
    update_public_experience_db,
    process_trigger_warnings,
    moderate_page,
    choose_moderation_redirect,
    extract_triggers_to_show,
    expand_filter,
    filter_by_tag,
    filter_by_moderation_status,
    filter_in_review,
    paginate_stories,
    get_latest_change_reply,
    structure_change_reply,
    number_stories,
    get_message,
    message_wrap,
    experience_titles_for_session,
    extract_authorship_details,
    get_carousel_stories,
    number_by_review_status,
    most_recent_exp_history,
    get_story_privacy_and_research_for_session,
    pick_research_message,
)

from server.apps.users.helpers import (
    user_profile_exists,
    get_user_profile,
    update_session_success_or_confirm,)

logger = logging.getLogger(__name__)

def about_us(request):
    return render(request, "main/about_us.html")


def what_autism_is(request):
    return render(request, "main/what_autism_is.html")


def help(request):
    return render(request, "main/help.html")


def content_moderation_guidelines(request):
    return render(request, "main/content_moderation_guidelines.html")

def participant_information(request):
    return render(request, "main/participant_information.html")

def edit_experience(request):
    return render(request, "main/share_experiences.html")


def signup(request):
    return render(request, "main/signup.html")


def registration(request):
    registration_status = True
    print(registration_status)
    return render(request, "main/registration.html", {"page_status": "registration"})

def success_confirm(request):
    """
    Flexible confirmation page
    """
    if request.user.is_authenticated:
        return render(request, "main/success_confirm.html")
    else:
        return redirect("index")


def logout_user(request):
    """
    Logout user
    """
    if request.user.is_authenticated:
        logout(request)
    return redirect("index")


# @vcr.use_cassette("tmp/overview.yaml", filter_query_parameters=['access_token'])
def index(request):
    """
    Starting page for app.
    """
    stories = get_carousel_stories()

    if request.user.is_authenticated:
        oh_member = request.user.openhumansmember

        context = {
            "oh_id": oh_member.oh_id,
            "oh_member": oh_member,
            "oh_user": oh_member.user,
            "oh_proj_page": settings.OH_PROJ_PAGE,
            "stories": stories,
        }
    else:
        auth_url = OpenHumansMember.get_auth_url()
        context = {
            "auth_url": auth_url,
            "oh_proj_page": settings.OH_PROJ_PAGE,
            "stories": stories,
        }
    return render(request, "main/home.html", context=context)

def login_user(request):
    """
    Page the user arrives at immediately after logging in, expected to
    immediately redirect to somewhere else.
    """
    if request.user.is_authenticated:
        if not user_profile_exists(user=request.user):
            # This is the first time we've logged into the site
            # We use update_or_create() rather than create() to avoid a race
            # condition on existence
            UserProfile.objects.update_or_create(user=request.user)
            return redirect("users:greetings")

    return redirect("main:index")

# @vcr.use_cassette("server/apps/main/tests/fixtures/share_exp.yaml", filter_query_parameters=['access_token', 'AWSAccessKeyId'])
def share_experience(request, uuid=False):
    """
    Form where users can share details of their experiences.
    """
    # if this is a POST request we need to process the form data
    if request.user.is_authenticated:
        if request.method == "POST":
            # create a form instance and populate it with data from the request:
            form = ShareExperienceForm(request.POST)
            # check whether it's valid:
            if form.is_valid():
                if uuid:
                    # we will be here if we are editing a record that already exists
                    # for OH we need to Delete before reupload.
                    request.user.openhumansmember.delete_single_file(
                        file_basename=f"{uuid}.json"
                    )
                    story_change_type = "edited"
                else:
                    uuid = make_uuid()
                    story_change_type = "new"

                upload(
                    data=form.cleaned_data,
                    uuid=uuid,
                    ohmember=request.user.openhumansmember,
                )
                profile = get_user_profile(request.user)
                if profile:
                    autistic_identification = profile.autistic_identification
                else:
                    autistic_identification = ""
                first_hand = form.cleaned_data['first_hand_authorship']

                research_message = pick_research_message(first_hand, autistic_identification)

                # Check the viewable and research options
                conf_story, pr, rr = get_story_privacy_and_research_for_session(data=form.cleaned_data, story_change_type=story_change_type)
                success_confirm_dict = update_session_success_or_confirm(source="experience", 
                                                                         confirm_story_response=conf_story, 
                                                                         public_response=pr, 
                                                                         research_response=rr,
                                                                         research_message=research_message,)

                for key in success_confirm_dict.keys():
                    if key in request.session:
                        del request.session[key]
                    request.session[key] = success_confirm_dict[key]

                # for Public Experience we need to check if it's viewable and update accordingly.
                update_public_experience_db(
                    data=form.cleaned_data,
                    uuid=uuid,
                    ohmember=request.user.openhumansmember,
                    editing_user=request.user.openhumansmember,
                )

                # redirect to a new URL:
                return redirect("main:success_confirm")
            # If form is invalid raise errors back to user
            else:
                for field in form:
                    for error in field.errors:
                        if field != "__all__":
                            messages.add_message(
                                request,
                                messages.WARNING,
                                "{}: {}".format(field.label, error),
                            )

                if uuid:  # check if editing existing exp
                    moderation_status = PublicExperience.objects.get(
                        experience_id=uuid
                    ).moderation_status
                    title = "Edit experience"
                    change_reply, changed_at = get_latest_change_reply(uuid)
                else:  # or creating new one
                    moderation_status = "not reviewed"
                    title = "Share experience"
                    change_reply = ""
                    changed_at = None
                return render(
                    request,
                    "main/share_experiences.html",
                    {
                        "form": form,
                        "uuid": uuid,
                        "title": title,
                        "moderation_status": moderation_status,
                        "change_reply": change_reply,
                        "changed_at": changed_at,
                    },
                )
        # if a GET (or any other method) we'll either create a blank form or
        # prepopulate form based on existing data.
        else:
            if uuid:
                # return data from oh.
                data = get_oh_combined(
                    ohmember=request.user.openhumansmember, uuid=uuid
                )
                form = ShareExperienceForm(data)
                title = "Edit experience"
                moderation_status = data.get("moderation_status", "not reviewed")
                change_reply, changed_at = get_latest_change_reply(uuid)
            else:
                form = ShareExperienceForm()
                title = "Share experience"
                moderation_status = "not reviewed"
                change_reply = ""
                changed_at = None

            return render(
                request,
                "main/share_experiences.html",
                {
                    "form": form,
                    "uuid": uuid,
                    "title": title,
                    "moderation_status": moderation_status,
                    "change_reply": change_reply,
                    "changed_at": changed_at,
                },
            )

    else:
        return registration(request)

server/apps/main/templates/main/partials/dummy_stories.html
<tr>
    <th scope="row">1</th>
    <td>Traffic Lights</td>
    <td>Self</td>
    <td>09-11-2021</td>
    <td>14-11-2021</td>
    <td>Accepted</td>
  </tr>
  <tr>
    <th scope="row">2</th>
    <td>Taking subways in London</td>
    <td>For autistic friend</td>
    <td>09-11-2021</td>
    <td>14-11-2021</td>
    <td>Moderating</td>
  </tr>
  <tr>
    <th scope="row">3</th>
    <td>Shopping in a market</td>
    <td>Self</td>
    <td>09-11-2021</td>
    <td>14-11-2021</td>
    <td>Re-moderating</td>
  </tr>

server/apps/main/templates/main/partials/footer.html
{% load static %}

  <div class="row">
    <div class="col-lg-3 footer-column">
      <a href="https://www.autistica.org.uk/"><img class="footer-image" src="{% static 'images/autistica.png' %}" width="65" height="40" alt="Autistica Logo" /></a>
      <a href="https://www.turing.ac.uk/"><img class="footer-image" src="{% static 'images/alanturing.png' %}" width="75" height="40" alt="Alan Turing Institute Logo" /></a>
      <p class="footer-text">&copy; Copyright 2024 AutSPACEs</p>
    </div>
    <div class="col-lg-3 footer-text">
      <h5>Supported by:</h5>
      <p><a href="https://www.autistica.org.uk/">Autistica</a></p>
      <p><a href="https://www.turing.ac.uk/">The Alan Turing Institute</a></p>
      <p><a href="https://www.openhumans.org/">Open Humans</a></p>
    </div>

    <div class="col-lg-3 footer-text">
      <h5>Policies</h5>
      <p><a href="{% url 'main:participant_information' %}">Participant information</a></p>
      <p><a href="{% url 'main:content_moderation_guidelines' %}">Content guidelines</a></p>
      <p><a href="https://github.com/alan-turing-institute/AutSPACEs/blob/main/code-of-conduct.md">Community code of conduct</a></p>
    </div>

    <div class="col-lg-3 footer-text">
    <h5>About us</h5>
      <p><a href="https://github.com/alan-turing-institute/AutSPACEs">GitHub</a></p>
      <p>Explore AutSPACEs</p>
      <p>Data usage</p>
    </div>
  </div>

server/apps/main/templates/main/partials/jquery.html
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>

server/apps/main/templates/main/partials/navigation.html
 {% load static %}
 {% load custom_tags %}
<div class="nav-section">
  <nav class="navbar navbar-expand-lg navbar-dark">
    <div class="container-fluid">
      <a class="navbar-brand nav-content" href="{% url 'index' %}">AutSPACEs</a>
      <button aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler"
              data-bs-target="#navbarText"
              data-bs-toggle="collapse" type="button">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link nav-link-menu" href="{% url 'main:share_exp' %}">Add stories</a>
          </li>
          <li class="nav-item">
            <a class="nav-link nav-link-menu" href="{% url 'main:public_experiences' %}">View stories</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link nav-link-menu" href="{% url 'main:my_stories' %}">My stories</a>
          </li>
          {% is_moderator user as moderator %}
          {% if moderator %}
          <li class="nav-item">
            <a class="nav-link nav-link-menu" href="{% url 'main:moderation_list' %}">Moderation</a>
          </li>
          {% endif %}
          {% endif %}
          <li class="nav-item dropdown">
            <a class="nav-link nav-link-menu dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
              data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Learn more
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <li><a class="dropdown-item" href="{% url 'main:what_autism_is' %}">About autism</a></li>
              <li><a class="dropdown-item" href="{% url 'main:about_us' %}">About AutSPACEs</a></li>
              <li><a class="dropdown-item" href="{% url 'main:content_moderation_guidelines' %}">Content guidelines</a></li>
              <li><a class="dropdown-item" href="{% url 'main:help' %}">Help</a></li>
            </ul>
          </li>
          <li class="nav-item">
            <a class="nav-link nav-link-menu" id="theme-toggle"><i class="bi bi-circle-half"></i> Switch light/dark</a>
          </li>
        </ul>



        {% if user.is_authenticated %}
        <li class="nav-item dropdown d-flex">
          <a class="nav-link nav-link-menu dropdown-toggle nav-account" href="#" id="accountDropdownMenuLink" role="button"
              data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Account
          </a>
            <ul class="dropdown-menu dropdown-menu-lg-end" aria-labelledby="accountDropdownMenuLink">
              <li><a class="dropdown-item" href="{% url 'users:profile' %}">Profile</a></li>
              <li>
                <form class="form-inline nav-nomargin" action="{% url 'main:logout' %}" method="post">
                  {% csrf_token %}
                  <button class="dropdown-item" type="submit">Log out</button>
                </form>
              </li>
            </ul>
        </li>
        {% elif not page_status == "registration" %}
        <li class="nav-item nav-content d-flex">
          <a class="nav-content nav-item btn nav-account" href="{{ auth_url }}">Log In</a>
        </li>
        <li class="nav-item d-flex">
          <a href="{% url 'main:registration' %}" class="nav-content nav-item btn btn-light">Register</a>
        </li>
        {% endif %}
      </div>
    </div>
  </nav>
</div>

<script src="{% static 'js/theme-checker.js' %}"></script>

server/apps/main/templates/main/partials/template_moderation_dropdown.html
{% load static %}

<!-- List of dropdown moderation replies with severity (amber/red) + link to CoC item  --> 

<template id="template-control" class="template-hidden">
    <div class="dropdown control">
      <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Reason for moderation
      </button>
      <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
        <li><a class="dropdown-item addreason" data-reason="Includes identity or sensitive data" data-href="identity" data-severity="red">Identity or sensitive data</a></li>
        <li><a class="dropdown-item addreason" data-reason="Discriminatory or belittling content" data-href="discriminatory" data-severity="red">Discriminatory or belittling</a></li>
        <li><a class="dropdown-item addreason" data-reason="Includes a racial slur" data-href="racial-slurs" data-severity="red">Racial slur</a></li>
        <li><a class="dropdown-item addreason" data-reason="Making assumptions when writing on behalf of others" data-href="are-you-making-assumptions" data-severity="red">Assumptions on behalf of others</a></li>
        <li><a class="dropdown-item addreason" data-reason="Including your own subjective details when writing on behalf of others" data-href="are-you-adding-subjective-detail" data-severity="red">Own subjectivity on behalf of others</a></li>
        <li><a class="dropdown-item addreason" data-reason="Responding to someone else's story" data-href="responding-to-others" data-severity="red">Response to someone else's story</a></li>
        <li><a class="dropdown-item addreason" data-reason="Includes swear words or disability slurs" data-href="swear-words" data-severity="amber">Swear words or disability slurs</a></li>
        <li><a class="dropdown-item addreason" data-reason="Potentially triggering to some users" data-href="swear-words" data-severity="amber">Triggering to some users</a></li>
      </ul>
    </div>
  </template>

server/apps/main/templates/main/partials/template_moderation_warnings.html
{% load static %}

<!-- moderation warning statuses to be displayed on conditions  --> 

<template id="template-text-not-reviewed-comments" class="template-hidden">
    <p>It's not possible to record <i>Moderation reasons</i> for stories that haven't been reviewed.</p>
    <p>Please set the <i>Moderation status</i> to <i>in review</i> to hold reasons for later use, or set the status to <i>accepted</i> or <i>rejected</i> to send the reasons to the author now.</p>
</template>

 <template id="template-text-reject-no-comments" class="template-hidden">
    <p>You are rejecting the story without providing a reason. Are you sure you want to continue?</p>
</template>

<template id="template-text-approve-comments" class="template-hidden">
    <p>When approving a story you can cite <span class="word-amber">Amber</span> reasons, but not <span class="word-red">Red</span> reasons. Stories containing <span class="word-red">Red</span> reasons must be rejected.</p>
</template>

server/apps/main/templates/main/partials/upload_form.html
<h2>Add your Experience</h2>

<form method="post" action="{% url 'main:upload' %}">
  {% csrf_token %}
  <div class="form-group">
    <label for="experience">Enter your experience</label>
    <textarea
      type="textarea"
      rows="5"
      class="form-control"
      id="experience"
      name="experience"
      placeholder="Your experience can be entered here"
    ></textarea>

    <label for="wish_different"
      >What would you have wished to be different?</label
    >
    <textarea
      type="textarea"
      rows="5"
      class="form-control"
      id="wish_different"
      name="wish_different"
      placeholder="Let us know what you would have wished to be differently in this experience."
    ></textarea>
  </div>

  <div class="form-check">
    <input
      class="form-check-input"
      name="research"
      type="checkbox"
      value="research"
      id="research"
    />
    <label class="form-check-label" for="research">
      Can be used for Research
    </label>
  </div>

  <div class="form-check">
    <input
      class="form-check-input"
      name="viewable"
      type="checkbox"
      value="viewable"
      id="viewable"
    />
    <label class="form-check-label" for="viewable">
      Is viewable by others
    </label>
  </div>

  <input class="btn btn-primary" type="submit" value="Share your Experience" />
</form>