server/apps/main/urls.py
from django.urls import path, re_path
from server.apps.main import views
from server.apps.main import feeds

app_name = "main"

urlpatterns = [
    re_path(r"^$", views.index, name="index"),
    re_path(r"^signup/?$", views.signup, name="signup"),
    re_path(r"^login/?$", views.login_user, name="login"),
    re_path(r"^logout/?$", views.logout_user, name="logout"),
    re_path(
        r"^public_experiences/?$",
        views.list_public_experiences,
        name="public_experiences",
    ),
    re_path(
        r"^moderate_public_experiences/?$",
        views.moderate_public_experiences,
        name="moderate_public_experiences",
    ),
    re_path(r"moderation_list/?$", views.moderation_list, name="moderation_list"),
    path("delete/<uuid>/", views.delete_experience, name="delete_exp"),
    path("share_exp/", views.share_experience, name="share_exp"),
    path("edit/<uuid>/", views.share_experience, name="edit_exp"),
    path("moderate/<uuid>/", views.moderate_experience, name="moderate_exp"),
    path("view/<uuid>/", views.view_experience, name="view_exp"),
    path("my_stories/", views.my_stories, name="my_stories"),
    path("about_us/", views.about_us, name="about_us"),
    path("what_autism_is/", views.what_autism_is, name="what_autism_is"),
    path("help/", views.help, name="help"),
    path("content_moderation_guidelines/", views.content_moderation_guidelines, name="content_moderation_guidelines"),
    path("participant_information/", views.participant_information, name="participant_information"),
    path("registration/", views.registration, name="registration"),
    path("single_story/<uuid>/",views.single_story,name="single_story"),
    path("success_confirm/", views.success_confirm, name="success_confirm"),
    path("public_experiences/rss.xml", feeds.PublicExperienceFeed(), name='rss_feed'),
    path("public_experiences/atom.xml", feeds.PublicExperienceAtomFeed(), name='atom_feed'),
]

server/apps/users/urls.py
from django.urls import path, re_path
from server.apps.users import views

app_name = "servers.apps.users"

urlpatterns = [
    path("profile/", views.user_profile, name="profile"),
    path("greetings/", views.user_profile, {"first_visit": True}, name="greetings"),
    path("delete/", views.user_profile_delete, name="delete"),
]

server/urls.py
"""
Main URL mapping configuration file.

Include other URLConfs from external apps using method `include()`.

It is also a good practice to keep a single URL to the root index page.

This examples uses Django's default media
files serving technique in development.
"""

from django.conf import settings
from django.contrib import admin
from django.contrib.admindocs import urls as admindocs_urls
from django.urls import include, path
from django.views.generic import TemplateView
from health_check import urls as health_urls

from server.apps.main import urls as main_urls
from server.apps.main.views import index
from server.apps.users import urls as users_urls

admin.autodiscover()

urlpatterns = [
    # Apps:
    path('main/', include(main_urls, namespace='main')),
    path('users/', include(users_urls, namespace='users')),

    # Health checks:
    path('health/', include(health_urls)),  # noqa: DJ05

    # django-admin:
    path('admin/doc/', include(admindocs_urls)),  # noqa: DJ05
    path('admin/', admin.site.urls),

    # Text and xml static files:
    path('robots.txt', TemplateView.as_view(
        template_name='txt/robots.txt',
        content_type='text/plain',
    )),
    path('humans.txt', TemplateView.as_view(
        template_name='txt/humans.txt',
        content_type='text/plain',
    )),

    # It is a good practice to have explicit index view:
    path('', index, name='index'),
]

# Appending url patterns for the prototype
urlpatterns += [
    path('openhumans/', include('openhumans.urls')),
]

if settings.DEBUG:  # pragma: no cover
    import debug_toolbar  # noqa: WPS433
    from django.conf.urls.static import static  # noqa: WPS433

    urlpatterns = [
        # URLs specific only to django-debug-toolbar:
        path('__debug__/', include(debug_toolbar.urls)),  # noqa: DJ05
    ] + urlpatterns + static(  # type: ignore
        # Serving media files in development only:
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

server/apps/users/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfile(models.Model):
    """
    Holds profile information about a user
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    profile_submitted = models.BooleanField(default=False)
    autistic_identification = models.TextField(default="")
    age_bracket = models.TextField(default="unspecified")
    age_public = models.BooleanField(default=False)
    gender = models.TextField(default="unspecified")
    gender_self_identification = models.TextField(default="")
    gender_public = models.BooleanField(default=False)
    description = models.TextField(default="")
    description_public = models.BooleanField(default=False)
    comms_review = models.BooleanField(default=False)

    abuse = models.BooleanField(default=False)
    violence = models.BooleanField(default=False)
    drug = models.BooleanField(default=False)
    mentalhealth = models.BooleanField(default=False)
    negbody = models.BooleanField(default=False)
    other = models.BooleanField(default=False)

    def __str__(self):
        return "Profile for {}".format(self.user.username)

server/apps/users/forms.py
from django import forms

class SelectRequired(forms.Select):
    # Disables items in the drop down list that have an empty value
    # See https://docs.djangoproject.com/en/4.2/ref/forms/renderers/#built-in-template-form-renderers
    # See also the ChoiceWidget.create_option() implementation in django/forms/widgets.py
    option_template_name = "users/select_option_disable_empty.html"

class UserProfileForm(forms.Form):

    autistic_identifications = [
        ("", "Please select"),
        ("yes", "Yes"),
        ("no", "No"),
        ("unspecified", "Prefer not to say"),
    ]
    
    autistic_identification = forms.ChoiceField(choices = autistic_identifications, widget = SelectRequired(attrs={
        "class": "form-select",
        "aria-describedby": "help_id_autistic_identification"}
        ),
                                           label="Do you identify as autistic?",
                                           help_text="AutSPACEs is focused on collecting and sharing the voices and lived experiences of autistic people, which is why we <strong>require a conscious decision for this question</strong>. If you select <i>prefer not to say</i>, your experiences will be considered as coming from a non-autistic person, labelled as such and can’t be used for research.",
                                           required=True,
                                           initial="")
    autistic_identification.group = 1

    age_brackets = [
        ("18-25", "18-25"),
        ("26-35", "26-35"),
        ("36-45", "36-45"),
        ("46-65", "46-65"),
        ("over 65", "Over 65"),
        ("unspecified", "Prefer not to say"),
    ]
    age_bracket = forms.ChoiceField(choices = age_brackets, widget = forms.Select(attrs={
        "class": "form-select",
        "aria-describedby": "help_id_age_bracket"}
        ), 
                                   required=False,
                                   label="What is your age group?",
                                   help_text="Sharing your age might help researchers understand potential trends across age groups. It can also help readers understand your perspective if this data is made public.",
                                   initial="unspecified")
    age_bracket.group = 1

    age_public = forms.BooleanField(label = "Make age public",
        required=False,
        widget=forms.CheckboxInput(attrs={"class": "form-check-input","type": "checkbox","role": "switch"}))
    age_public.group = 1
    age_public.gap = True

    genders = [
        ("nonbinary", "Non-binary"),
        ("female", "Female"),
        ("male", "Male"),
        ("self_identify", "Self identify"),
        ("unspecified", "Prefer not to say"),
    ]
    gender = forms.ChoiceField(choices = genders, widget = forms.Select(attrs={
        "class": "form-select",
        "aria-describedby": "help_id_gender"}
        ), 
                              required=False,
                              label="What gender do you identify with?",
                              help_text="Sharing your gender identity might help researchers understand potential trends across different demographics. It can also help readers understand your perspective if this data is made public. You can also choose to self-identify instead of using one of the pre-given options.",
                              initial="unspecified")
    gender.group = 1


    gender_self_identification = forms.CharField(label="Self identification",
                                 max_length=150, strip=True, required=False,
                                 widget=forms.TextInput())

    gender_self_identification.group = 1
    gender_self_identification.layout_horizontal = True

    gender_public = forms.BooleanField(label = "Make gender public",
        required=False,
        widget=forms.CheckboxInput(attrs={"class": "form-check-input","type": "checkbox","role": "switch"}))

    gender_public.group = 1
    gender_public.gap = True

    description = forms.CharField(label="What else would you like researchers (or readers) to know about you?",
                                 max_length=2048, strip=True, required=False,
                                 help_text="""
                                    You can provide any additional context here that you deem relevant to understanding your perspective and experiences. 
                                    This could be your ethnicity, where you grew up, your educational background, or when and how you (self-)diagnosed. 
                                    The AutSPACEs team might use this information to refine the structured demographic questions above. 
                                    You can also make this information publicly accessible, and it might be linked to your public experiences in the future.
                                 """,
                                 widget=forms.Textarea(attrs={"placeholder":"Optionally share more about yourself",
                                                              "rows":"4",
                                                              "class":"form-control",
                                                              "aria-describedby": "help_id_description"}))
    description.group = 1

    description_public = forms.BooleanField(label = "Make description public",
        required=False,
        widget=forms.CheckboxInput(attrs={"class": "form-check-input","type": "checkbox","role": "switch"}))
    description_public.group = 1

    # Add triggering here
    abuse = forms.BooleanField(label = "Abuse (physical, sexual, emotional and verbal)",
        required=False,
        widget=forms.CheckboxInput(attrs={"class": "form-check-input","type": "checkbox","role": "switch"}))
    abuse.group = 2
    violence = forms.BooleanField(label = "Violence and assault",
        required=False,
        widget=forms.CheckboxInput(attrs={"class": "form-check-input","type": "checkbox","role": "switch"}))
    violence.group = 2
    drug = forms.BooleanField(label = "Drug and/or alcohol misuse",
        required=False,
        widget=forms.CheckboxInput(attrs={"class": "form-check-input","type": "checkbox","role": "switch"}))
    drug.group = 2
    mentalhealth = forms.BooleanField(label = "Mental health issues",
        required=False,
        widget=forms.CheckboxInput(attrs={"class": "form-check-input","type": "checkbox","role": "switch"}))
    mentalhealth.group = 2
    negbody = forms.BooleanField(label = "Negative body image",
        required=False,
        widget=forms.CheckboxInput(attrs={"class": "form-check-input","type": "checkbox","role": "switch"}))
    negbody.group = 2
    other = forms.BooleanField(label = "Other",
        required=False,
        widget=forms.CheckboxInput(attrs={"class": "form-check-input","type": "checkbox","role": "switch"}))
    other.group = 2

    # Communications preferences
    comms_review = forms.BooleanField(label = "Moderation reviews of my experiences",
        required = False,
        widget=forms.CheckboxInput(attrs={"class": "form-check-input","type": "checkbox","role": "switch"}))
    comms_review.group = 3

    # New user management
    profile_submitted = forms.BooleanField(label = "Profile submitted",
        required=False,
        widget=forms.CheckboxInput(attrs={"class": "form-check-input","type": "checkbox","role": "switch"}))
    profile_submitted.group = "hidden"

class UserProfileDeleteForm(forms.Form):
    delete_oh_data = forms.BooleanField(label = "Delete your stories from OpenHumans",
                                       required=False,
                                       widget=forms.CheckboxInput(attrs={
                                           "class": "form-check-input",
                                           "type": "checkbox",
                                           "role": "switch"
                                           }))

server/apps/users/views.py
import logging

from django.shortcuts import render
from django.conf import settings
from django.shortcuts import redirect, render
from django.contrib import messages
from django.forms.models import model_to_dict
from django.contrib.auth import logout

from .models import UserProfile
from .forms import (
    UserProfileForm,
    UserProfileDeleteForm,
)
from .helpers import (
    user_profile_exists,
    get_user_profile,
    delete_user,
    update_session_success_or_confirm,
)


logger = logging.getLogger(__name__)

def user_profile(request, first_visit=False):
    """
    User profile page.
    """
    if request.user.is_authenticated:
        if request.method == "POST":
            form = UserProfileForm(request.POST)

            if form.is_valid():
                # Update the status to indicate the user has submitted at least once
                form.cleaned_data["profile_submitted"] = True
                UserProfile.objects.update_or_create(user=request.user, defaults=form.cleaned_data)

                success_confirm_dict = update_session_success_or_confirm(source="profile")

                for key in success_confirm_dict.keys():
                    if key in request.session:
                        del request.session[key]
                    request.session[key] = success_confirm_dict[key]

            return redirect("main:success_confirm")
        else:
            profile = get_user_profile(request.user)
            if profile:
                data = model_to_dict(profile)
                # If the profile has been submitted this can't be the user's first visit
                first_visit &= not profile.profile_submitted
                form = UserProfileForm(data)
            else:
                form = UserProfileForm()
            oh_member = request.user.openhumansmember
            return render(
                request, "users/profile.html", {
                    "title": "Profile",
                    "form": form,
                    "oh_id": oh_member.oh_id,
                    "first_visit": first_visit,
                    "request_profile": False,
                })
    else:
        return redirect("index")

def user_profile_delete(request):
    if request.user.is_authenticated:
        oh_member = request.user.openhumansmember
        if request.method == "POST":
            form = UserProfileDeleteForm(request.POST)

            if form.is_valid():
                # Delete all the user's data
                delete_oh_data = form.cleaned_data['delete_oh_data']
                delete_user(request.user, delete_oh_data)
                # Log the user out. That's it.
                logout(request)
                # Say goodbye.
                return render(
                    request, "users/goodbye.html", {
                        "title": "Profile Deleted",
                        "delete_oh_data": delete_oh_data,
                    })
        else:
            form = UserProfileDeleteForm()

        return render(
            request, "users/delete.html", {
                "title": "Delete profile",
                "form": form,
                "oh_id": oh_member.oh_id,
            })

    else:
        return redirect("index")

server/apps/users/templates/users/delete.html
{% extends 'main/application.html' %}

{% block title %}AutSPACEs - {{title}} {% endblock %}

{% load static %}
{% load custom_tags %}
{% load humanize %}

{% block content %}

<!-- Delete User Profile Form -->
<section id="delete-user-profile-form">
  <div class="container profile-section">
    <h3><label>Delete AutSPACEs account</label></h3>
    <p/><a href="https://www.openhumans.org/">OpenHumans</a> ID: {{ oh_id }}

    <p/>Are you sure you want to delete your AutSPACEs account?
    <p/>This will remove all your data from the AutSPACEs platform. This process cannot be undone.
    <p/>Select the switch below to also remove your stories from OpenHumans.
    <form action="{% url 'users:delete' %}" class="form-context" method="post">
      {% csrf_token %}
      <div class="form-group">
        {% for field in form %}
          <div class="row">
            <div class="form-check col-lg-12">
              <div class="form-check form-switch">
                {{ field }}
                <label class="form-check-label" for="{{ field.auto_id}}">{{ field.label }}</label>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
      <div class="form-group">
        <button type="submit" class="btn btn-danger" id="submitForm">Delete account</button>
        <a role="button" class="btn btn-secondary ml-5" id="cancelForm" href="{% url 'users:profile' %}">Cancel</a>
      </div>
    </form>
  </div>
</section>

{% endblock %}

server/apps/users/templates/users/goodbye.html
{% extends 'main/application.html' %}

{% block title %}AutSPACEs - {{title}} {% endblock %}

{% load static %}
{% load custom_tags %}
{% load humanize %}

{% block content %}

<!-- User Profile Deleted Page -->
<section id="goodbye-notification">
  <div class="container profile-section">
    <h3><label>Thank you for contributing to AutSPACEs</label></h3>

    <p/>We're sorry to see you go, but are grateful for your contribution to AutSPACEs.
    {% if delete_oh_data %}
      <p/>All of your personal data has been removed from the AutSPACEs platform and your stories have been removed from <a href="https://www.openhumans.org/">OpenHumans</a>. This won't affect any other data you may have stored on the OpenHumans platform.
    {% else %}
      <p/>All of your personal data has been removed from the AutSPACEs platform, but please be aware that stories you entered here may still be stored on <a href="https://www.openhumans.org/">OpenHumans</a>. You'll need to delete these separately.
    {% endif %}
    <p/>If you'd like to contribute to AutSPACEs again in the future, please feel free to create a new account.
    <div class="form-group">
      <a role="button" class="btn btn-primary" id="return" href="{% url 'index' %}">Return to front page</a>
    </div>
  </div>
</section>

{% endblock %}

server/apps/users/templates/users/profile.html
{% extends 'main/application.html' %}

{% block title %}AutSPACEs - {{title}} {% endblock %}

{% load static %}
{% load custom_tags %}
{% load humanize %}

{% block content %}

<script src="{% static 'js/activate-profile.js' %}"></script>

{% if first_visit == True %}
<div class="container alert-container">
  <div class="alert alert-info" role="alert">
    Welcome to AutSPACEs!
  </div>
  <div class="alert alert-info" role="alert">
    We&#x27;re super excited to have you here. As this is your first visit,
    please take the time to complete your profile as this helps us and others make 
    the most of the experiences you share. Return here to update your details at any time.
  </div>
</div>
{% endif %}
{% if request_profile == True %}
<div class="container alert-container">
  <div class="alert alert-info" role="alert">
    We&#x27;d love it if you could fill out some of your details, to allow us and
    others to make the most of your shared experiences. 
    You can come back here to update your details at any time.
  </div>
</div>
{% endif %}

<!-- User Profile Form -->
<section id="user-profile-form">
  <div class="container profile-section">
    <form action="{% url 'users:profile' %}" class="form-context needs-validation" method="post" novalidate>
    {% csrf_token %}
    {% regroup form by field.group as field_groups %}

    {% for group in field_groups %}
      {% define "col-lg-12" as columns %}
      {% if group.grouper == 1 %}
        {% define "Your profile" as header %}
        {% define "You can choose <em>'Prefer not to say'</em> for all options, and answers are not public by default." as subheader %}
      {% endif %}
      {% if group.grouper == 2 %}
        {% define "Sensitive topics" as header %}
        {% define "Select which sensitive topics should be visible as your default." as subheader %}
        {% define "col-lg-6" as columns %}
      {% endif %}
      {% if group.grouper == 3 %}
        {% define "Messaging options" as header %}
        {% define "Select when you would like to be notified by us." as subheader %}
      {% endif %}
      {% if group.grouper == 4 %}
        {% define "Hidden fields" as header %}
        {% define "These fields are for debugging only and will be removed in the final implementation" as subheader %}
      {% endif %}
      {% if group.grouper != "hidden" %}
      <div class="form-group">
        <h3><label>{{ header }}</label></h3>

        <h5>{{ subheader }}</h5>

        {% if group.grouper == 2 %}
        <p>
          <small id="help_{{field.auto_id}}" class="form-text form-text-color">
            You can modify these defaults at any time. You can also override the defaults from the <i>View stories</i> page.
          </small>
        </p>
        {% endif %}

        <div class="form-row">
        {% for field in group.list %}
          <div class="col {{ columns }}">
          {% if field.field.widget|field_type == "CheckboxInput" %}
              <div class="form-check form-switch">
                {{ field }}
                <label class="form-check-label" for="{{ field.auto_id }}">{{ field.label }}</label>
              </div>
          {% else %}
              <p/><label for="{{ field.auto_id }}">{{ field.label }}</label>
              {{ field }}
              {% if field.help_text %}
              <small id="help_{{field.auto_id}}" class="form-text form-text-color">
                {{field.help_text|safe}}
              </small>
              {% endif %}
          {% endif %}
          </div>
          {% if field.field.gap %}
            <div class="form-check {{ columns }} mb-3"></div>
          {% endif %}
        {% endfor %}
        </div>
      </div>
      {% endif %}
    {% endfor %}

      <div class="form-group">
        <button type="submit" class="btn btn-primary" id="submitForm">Save profile settings</button>
      </div>
    </form>

    <h3><label>Account details</label></h3>
    <p/><a href="https://www.openhumans.org/">Open Humans</a> ID: {{ oh_id }}
    <p/><a href="{% url 'users:delete' %}" class="btn btn-danger">Delete AutSPACEs account</a>


  </div>
</section>

{% endblock %}

server/apps/users/templates/users/select_option_disable_empty.html
<option value="{{ widget.value|stringformat:'s' }}"{% include "django/forms/widgets/attrs.html" %}{% if widget.value|stringformat:'s' == '' %} disabled="disabled"{% endif %}>{{ widget.label }}</option>

server/apps/users/templates/users/tmp_confirm_profile_save.html
{% extends 'main/application.html' %}

{% block title %}AutSPACEs - {% firstof request.session.s_or_c_title " " %} {% endblock %}

{% load static %}
{% load custom_tags %}
{% load humanize %}

{% block content %}


<section class="confirmation">
    <div class="confirmation-container">
      <div class="confirm_success">
        <h1 class="big-heading title-text-yellow">
          {% firstof request.session.s_or_c_header "unknown headline" %}
        </h1>
  
        <p class="confirmation-title-text">
          {% firstof request.session.s_or_c_subheader "unknown subheadline" %}
        </p>
      </div>
   </div>
      <div class="what-now-section">
        <p class="confirmation-section-heading">
          What happens now ?</p>
        <div class="what-now-text">
            <ul>
            <li><p class="text">
              {% firstof request.session.s_or_c_whn_1 "First line of what happens now" %}
            </p></li>
  
            <li><p class="text">
              {% firstof request.session.s_or_c_whn_2 "Second line of what happens now"%}
            </p></li>
            <li><p class="text">
              {% firstof request.session.s_or_c_whn_3 "Third line of what happens now"%}
            </p></li>
              </ul>
        </div>
      </div>
  
      <div class="to-do-container">
        <p class="to-do-heading">
          What would you like to do next ?
        </p>
  
        <div class="btn-class-confirmationpage">
          {% if request.session.success_or_confirm == "profile" %}
            <a href="{% url 'users:profile' %}" class="btn btn-outline-primary btn-lg btn-confirmationpage">
              Visit My Profile
            </a>
          {% else %}
          <a href="{% url 'main:share_exp' %}" class="btn btn-outline-primary btn-lg btn-confirmationpage">
            Enter Another Experience
          </a>
          {% endif %}
  
          <a href="{% url 'main:my_stories' %}" class="btn btn-outline-primary btn-lg btn-confirmationpage">
            Go To My Stories
          </a>
  
          <a href="{% url 'main:public_experiences' %}" class="btn btn-outline-primary btn-lg btn-confirmationpage">
            View Other Stories
          </a>
  
          <a href="{% url 'main:about_us' %}" class="btn btn-outline-primary btn-lg btn-confirmationpage">
            Find Out More About AutSPACEs
          </a>
  
        </div>
      </div>
    </div>
  
  </section>
  </div>
  
  {% endblock %}
  