server/apps/main/urls.py
from django.urls import path, re_path
from server.apps.main import views
from server.apps.main import feeds

app_name = "main"

urlpatterns = [
    re_path(r"^$", views.index, name="index"),
    re_path(r"^signup/?$", views.signup, name="signup"),
    re_path(r"^login/?$", views.login_user, name="login"),
    re_path(r"^logout/?$", views.logout_user, name="logout"),
    re_path(
        r"^public_experiences/?$",
        views.list_public_experiences,
        name="public_experiences",
    ),
    re_path(
        r"^moderate_public_experiences/?$",
        views.moderate_public_experiences,
        name="moderate_public_experiences",
    ),
    re_path(r"moderation_list/?$", views.moderation_list, name="moderation_list"),
    path("delete/<uuid>/", views.delete_experience, name="delete_exp"),
    path("share_exp/", views.share_experience, name="share_exp"),
    path("edit/<uuid>/", views.share_experience, name="edit_exp"),
    path("moderate/<uuid>/", views.moderate_experience, name="moderate_exp"),
    path("view/<uuid>/", views.view_experience, name="view_exp"),
    path("my_stories/", views.my_stories, name="my_stories"),
    path("about_us/", views.about_us, name="about_us"),
    path("what_autism_is/", views.what_autism_is, name="what_autism_is"),
    path("help/", views.help, name="help"),
    path("content_moderation_guidelines/", views.content_moderation_guidelines, name="content_moderation_guidelines"),
    path("participant_information/", views.participant_information, name="participant_information"),
    path("registration/", views.registration, name="registration"),
    path("single_story/<uuid>/",views.single_story,name="single_story"),
    path("success_confirm/", views.success_confirm, name="success_confirm"),
    path("public_experiences/rss.xml", feeds.PublicExperienceFeed(), name='rss_feed'),
    path("public_experiences/atom.xml", feeds.PublicExperienceAtomFeed(), name='atom_feed'),
]

server/apps/users/urls.py
from django.urls import path, re_path
from server.apps.users import views

app_name = "servers.apps.users"

urlpatterns = [
    path("profile/", views.user_profile, name="profile"),
    path("greetings/", views.user_profile, {"first_visit": True}, name="greetings"),
    path("delete/", views.user_profile_delete, name="delete"),
]

server/urls.py
"""
Main URL mapping configuration file.

Include other URLConfs from external apps using method `include()`.

It is also a good practice to keep a single URL to the root index page.

This examples uses Django's default media
files serving technique in development.
"""

from django.conf import settings
from django.contrib import admin
from django.contrib.admindocs import urls as admindocs_urls
from django.urls import include, path
from django.views.generic import TemplateView
from health_check import urls as health_urls

from server.apps.main import urls as main_urls
from server.apps.main.views import index
from server.apps.users import urls as users_urls

admin.autodiscover()

urlpatterns = [
    # Apps:
    path('main/', include(main_urls, namespace='main')),
    path('users/', include(users_urls, namespace='users')),

    # Health checks:
    path('health/', include(health_urls)),  # noqa: DJ05

    # django-admin:
    path('admin/doc/', include(admindocs_urls)),  # noqa: DJ05
    path('admin/', admin.site.urls),

    # Text and xml static files:
    path('robots.txt', TemplateView.as_view(
        template_name='txt/robots.txt',
        content_type='text/plain',
    )),
    path('humans.txt', TemplateView.as_view(
        template_name='txt/humans.txt',
        content_type='text/plain',
    )),

    # It is a good practice to have explicit index view:
    path('', index, name='index'),
]

# Appending url patterns for the prototype
urlpatterns += [
    path('openhumans/', include('openhumans.urls')),
]

if settings.DEBUG:  # pragma: no cover
    import debug_toolbar  # noqa: WPS433
    from django.conf.urls.static import static  # noqa: WPS433

    urlpatterns = [
        # URLs specific only to django-debug-toolbar:
        path('__debug__/', include(debug_toolbar.urls)),  # noqa: DJ05
    ] + urlpatterns + static(  # type: ignore
        # Serving media files in development only:
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

server/apps/main/models.py
from django.db import models
from openhumans.models import OpenHumansMember


class PublicExperience(models.Model):
    experience_text = models.TextField()
    difference_text = models.TextField(default="")
    title_text = models.TextField(default="")
    created_at = models.DateTimeField(auto_now=True)
    experience_id = models.TextField(primary_key=True) #if specified as primary key you cannot have duplicates.
    open_humans_member = models.ForeignKey(OpenHumansMember,
                                           blank=True, null=True,
                                           on_delete=models.CASCADE)
    moderation_status = models.CharField(
        blank=False,
        default='not reviewed',
        max_length=50)
    
    abuse = models.BooleanField(default=False)
    violence = models.BooleanField(default=False)
    drug = models.BooleanField(default=False)
    mentalhealth = models.BooleanField(default=False)
    negbody = models.BooleanField(default=False)
    other = models.TextField(default="")
    
    research = models.BooleanField(default=False)

    authorship_choices = ((False, "Experience is someone else's"), (True, "Experience is my own"))
    first_hand_authorship = models.BooleanField(choices=authorship_choices, default=False)
    authorship_relation = models.TextField(default="")

    def __str__(self):
        return self.experience_text

class ExperienceHistory(models.Model):
    experience = models.ForeignKey(PublicExperience, on_delete=models.CASCADE)
    change_type = models.TextField()
    changed_at = models.DateTimeField(auto_now=True)
    changed_by = models.ForeignKey(OpenHumansMember, 
                                   blank=False,
                                   null=False,
                                   on_delete=models.CASCADE)
    change_comments = models.TextField(default="")
    change_reply = models.TextField(default="")

    def __str__(self):
        return self.change_type

server/apps/main/views.py
import io
import json
import logging
import vcr

import requests
from django.conf import settings
from django.contrib.auth import logout
from django.shortcuts import redirect, render
from openhumans.models import OpenHumansMember
from django.db.models import Q
from django.urls import reverse
from django.core.paginator import Paginator
from django.core.exceptions import ObjectDoesNotExist
from django.forms.models import model_to_dict

from .models import PublicExperience, ExperienceHistory
from server.apps.users.models import UserProfile

from .forms import ShareExperienceForm, ModerateExperienceForm

from django.contrib import messages

from server.apps.main.helpers import (
    is_moderator,
    public_experience_model_to_form,
    extract_experience_details,
    reformat_date_string,
    get_review_status,
    get_oh_combined,
    delete_single_file_and_pe,
    upload,
    rebuild_experience_data,
    make_uuid,
    delete_PE,
    update_public_experience_db,
    process_trigger_warnings,
    moderate_page,
    choose_moderation_redirect,
    extract_triggers_to_show,
    expand_filter,
    filter_by_tag,
    filter_by_moderation_status,
    filter_in_review,
    paginate_stories,
    get_latest_change_reply,
    structure_change_reply,
    number_stories,
    get_message,
    message_wrap,
    experience_titles_for_session,
    extract_authorship_details,
    get_carousel_stories,
    number_by_review_status,
    most_recent_exp_history,
    get_story_privacy_and_research_for_session,
    pick_research_message,
)

from server.apps.users.helpers import (
    user_profile_exists,
    get_user_profile,
    update_session_success_or_confirm,)

logger = logging.getLogger(__name__)

def about_us(request):
    return render(request, "main/about_us.html")


def what_autism_is(request):
    return render(request, "main/what_autism_is.html")


def help(request):
    return render(request, "main/help.html")


def content_moderation_guidelines(request):
    return render(request, "main/content_moderation_guidelines.html")

def participant_information(request):
    return render(request, "main/participant_information.html")

def edit_experience(request):
    return render(request, "main/share_experiences.html")


def signup(request):
    return render(request, "main/signup.html")


def registration(request):
    registration_status = True
    print(registration_status)
    return render(request, "main/registration.html", {"page_status": "registration"})

def success_confirm(request):
    """
    Flexible confirmation page
    """
    if request.user.is_authenticated:
        return render(request, "main/success_confirm.html")
    else:
        return redirect("index")


def logout_user(request):
    """
    Logout user
    """
    if request.user.is_authenticated:
        logout(request)
    return redirect("index")


# @vcr.use_cassette("tmp/overview.yaml", filter_query_parameters=['access_token'])
def index(request):
    """
    Starting page for app.
    """
    stories = get_carousel_stories()

    if request.user.is_authenticated:
        oh_member = request.user.openhumansmember

        context = {
            "oh_id": oh_member.oh_id,
            "oh_member": oh_member,
            "oh_user": oh_member.user,
            "oh_proj_page": settings.OH_PROJ_PAGE,
            "stories": stories,
        }
    else:
        auth_url = OpenHumansMember.get_auth_url()
        context = {
            "auth_url": auth_url,
            "oh_proj_page": settings.OH_PROJ_PAGE,
            "stories": stories,
        }
    return render(request, "main/home.html", context=context)

def login_user(request):
    """
    Page the user arrives at immediately after logging in, expected to
    immediately redirect to somewhere else.
    """
    if request.user.is_authenticated:
        if not user_profile_exists(user=request.user):
            # This is the first time we've logged into the site
            # We use update_or_create() rather than create() to avoid a race
            # condition on existence
            UserProfile.objects.update_or_create(user=request.user)
            return redirect("users:greetings")

    return redirect("main:index")

# @vcr.use_cassette("server/apps/main/tests/fixtures/share_exp.yaml", filter_query_parameters=['access_token', 'AWSAccessKeyId'])
def share_experience(request, uuid=False):
    """
    Form where users can share details of their experiences.
    """
    # if this is a POST request we need to process the form data
    if request.user.is_authenticated:
        if request.method == "POST":
            # create a form instance and populate it with data from the request:
            form = ShareExperienceForm(request.POST)
            # check whether it's valid:
            if form.is_valid():
                if uuid:
                    # we will be here if we are editing a record that already exists
                    # for OH we need to Delete before reupload.
                    request.user.openhumansmember.delete_single_file(
                        file_basename=f"{uuid}.json"
                    )
                    story_change_type = "edited"
                else:
                    uuid = make_uuid()
                    story_change_type = "new"

                upload(
                    data=form.cleaned_data,
                    uuid=uuid,
                    ohmember=request.user.openhumansmember,
                )
                profile = get_user_profile(request.user)
                if profile:
                    autistic_identification = profile.autistic_identification
                else:
                    autistic_identification = ""
                first_hand = form.cleaned_data['first_hand_authorship']

                research_message = pick_research_message(first_hand, autistic_identification)

                # Check the viewable and research options
                conf_story, pr, rr = get_story_privacy_and_research_for_session(data=form.cleaned_data, story_change_type=story_change_type)
                success_confirm_dict = update_session_success_or_confirm(source="experience", 
                                                                         confirm_story_response=conf_story, 
                                                                         public_response=pr, 
                                                                         research_response=rr,
                                                                         research_message=research_message,)

                for key in success_confirm_dict.keys():
                    if key in request.session:
                        del request.session[key]
                    request.session[key] = success_confirm_dict[key]

                # for Public Experience we need to check if it's viewable and update accordingly.
                update_public_experience_db(
                    data=form.cleaned_data,
                    uuid=uuid,
                    ohmember=request.user.openhumansmember,
                    editing_user=request.user.openhumansmember,
                )

                # redirect to a new URL:
                return redirect("main:success_confirm")
            # If form is invalid raise errors back to user
            else:
                for field in form:
                    for error in field.errors:
                        if field != "__all__":
                            messages.add_message(
                                request,
                                messages.WARNING,
                                "{}: {}".format(field.label, error),
                            )

                if uuid:  # check if editing existing exp
                    moderation_status = PublicExperience.objects.get(
                        experience_id=uuid
                    ).moderation_status
                    title = "Edit experience"
                    change_reply, changed_at = get_latest_change_reply(uuid)
                else:  # or creating new one
                    moderation_status = "not reviewed"
                    title = "Share experience"
                    change_reply = ""
                    changed_at = None
                return render(
                    request,
                    "main/share_experiences.html",
                    {
                        "form": form,
                        "uuid": uuid,
                        "title": title,
                        "moderation_status": moderation_status,
                        "change_reply": change_reply,
                        "changed_at": changed_at,
                    },
                )
        # if a GET (or any other method) we'll either create a blank form or
        # prepopulate form based on existing data.
        else:
            if uuid:
                # return data from oh.
                data = get_oh_combined(
                    ohmember=request.user.openhumansmember, uuid=uuid
                )
                form = ShareExperienceForm(data)
                title = "Edit experience"
                moderation_status = data.get("moderation_status", "not reviewed")
                change_reply, changed_at = get_latest_change_reply(uuid)
            else:
                form = ShareExperienceForm()
                title = "Share experience"
                moderation_status = "not reviewed"
                change_reply = ""
                changed_at = None

            return render(
                request,
                "main/share_experiences.html",
                {
                    "form": form,
                    "uuid": uuid,
                    "title": title,
                    "moderation_status": moderation_status,
                    "change_reply": change_reply,
                    "changed_at": changed_at,
                },
            )

    else:
        return registration(request)

server/apps/main/templates/main/flex_success_confirm.html
{% extends 'main/application.html' %}

{% block title %}AutSPACEs - {% firstof request.session.s_or_c_title " " %} {% endblock %}

{% load static %}
{% load custom_tags %}
{% load humanize %}

{% block content %}


<section class="confirmation">
    <div class="confirmation-container">
      <div class="confirm_success">
        <h1 class="big-heading title-text-yellow">
          {% firstof request.session.s_or_c_header "unknown headline" %}
        </h1>
  
        <p class="confirmation-title-text">
          {% firstof request.session.s_or_c_subheader "unknown subheadline" %}
        </p>
      </div>
   </div>
      <div class="what-now-section">
        <p class="confirmation-section-heading">
          What happens now ?</p>
        <div class="what-now-text">
            <ul>
            <li><p class="text">
              {% firstof request.session.s_or_c_whn_1 "First line of what happens now" %}
            </p></li>
  
            <li><p class="text">
              {% firstof request.session.s_or_c_whn_2 "Second line of what happens now"%}
            </p></li>
            <li><p class="text">
              {% firstof request.session.s_or_c_whn_3 "Third line of what happens now"%}
            </p></li>
              </ul>
        </div>
      </div>
  
      <div class="to-do-container">
        <p class="to-do-heading">
          What would you like to do next ?
        </p>
  
        <div class="btn-class-confirmationpage">
          {% if request.session.success_or_confirm == "profile" %}
            <a href="{% url 'users:profile' %}" class="btn btn-outline-primary btn-lg btn-confirmationpage">
              Visit My Profile
            </a>
          {% else %}
          <a href="{% url 'main:share_exp' %}" class="btn btn-outline-primary btn-lg btn-confirmationpage">
            Enter Another Experience
          </a>
          {% endif %}
  
          <a href="{% url 'main:my_stories' %}" class="btn btn-outline-primary btn-lg btn-confirmationpage">
            Go To My Stories
          </a>
  
          <a href="{% url 'main:public_experiences' %}" class="btn btn-outline-primary btn-lg btn-confirmationpage">
            View Other Stories
          </a>
  
          <a href="{% url 'main:about_us' %}" class="btn btn-outline-primary btn-lg btn-confirmationpage">
            Find Out More About AutSPACEs
          </a>
  
        </div>
      </div>
    </div>
  
  </section>
  </div>
  
  {% endblock %}
  

server/apps/main/templates/main/share_experiences.html
{% extends 'main/application.html' %}

{% block title %}AutSPACEs - {{title}} {% endblock %}

{% load static %}
{% load custom_tags %}
{% load humanize %}

{% block content %}

<!--Share Experiences Form-->
<div class="container">
<section id="share-form">
  <div class="row">
    <div class="container read-before-container" id="accordion">
      <div class="card">
        <div class="card-header" id="headingOne">
          <h5 class="mb-0">
            <button aria-controls="collapseOne" aria-expanded="false" class="btn btn-link collapsed"
                    data-bs-target="#collapseOne" data-bs-toggle="collapse">
              Read this first
            </button>
          </h5>
        </div>
        <div aria-labelledby="headingOne" class="collapse" data-bs-parent="#accordion" id="collapseOne">
          <div class="card-body">
            <strong>What is AutSPACEs?</strong>
            <p>
              AutSPACEs is an online space which puts autistic people first. 
              We’re committed to providing a safe and welcoming place for autistic people 
              and supporters to share experiences, knowing your voices will be heard and your contributions recognised.
            </p>
            <p>
              AutSPACEs allows users to share stories publicly with other users as well as privately with researchers. 
              To ensure it is a respectful and welcoming place for autistic people and other members of the community, 
              everyone sharing a story publicly will be required to follow our 
              <a href="{% url 'main:content_moderation_guidelines' %}"
               target="_blank">content guidelines</a>.
            </p>
            <p>
              Before a story can be published, it will be reviewed by a moderator to check it adheres to these guidelines. 
              If it doesn’t, you can choose for the story to remain private or to edit and resubmit it.
            </p>
            <strong>What are sensory experiences?</strong>
            <p>
              Autistic people often have senses that are weaker or stronger than those of non-autistic people. 
              This is one of the reasons navigating and coping in the world can be very difficult.
            </p>
            <p>
              </br>Sight, hearing, smell, taste and touch are not the only senses. Others include:
            <ul>
              <li>The sense of your body, its movement and position, known as proprioception;</li>
              <li>The sense of balance, or equilibrioception;</li>
              <li>The perception of pain, or nociception;</li>
              <li>The perception of hot and cold, or thermoception;</li>
              <li>The sense of time passing, or chromoception.</li>
            </ul>
            </p>
              <a href="{% url 'main:help' %}"
               target="_blank">
              <button class="btn btn-outline-primary coc-btn float-end">Read more</button>
            </a>
          </div>
        </div>
      </div>
      <div class="card">
        <div class="card-header" id="headingTwo">
          <h5 class="mb-0">
            <button aria-controls="collapseTwo" aria-expanded="false" class="btn btn-link collapsed"
                    data-bs-target="#collapseTwo" data-bs-toggle="collapse">
              Labels for sensitive topics
            </button>
          </h5>
        </div>
        <div aria-labelledby="headingTwo" class="collapse" data-bs-parent="#accordion" id="collapseTwo">
          <div class="card-body">
            <strong>What are trigger labels?</strong>
            <p>
              AutSPACEs is interested in sensory experiences across a wide range of situations and impacts. 
              This includes potentially challenging or distressing experiences. 
              So readers see those stories only when they’re ready for them, 
              we ask users to label potentially sensitive topics.
            </p>
            <strong>These include:</strong>
            <ul>
              <li>Abuse (physical, sexual, emotional and verbal)</li>
              <li>Violence and assault</li>
              <li>Drug and/or alcohol misuse</li>
              <li>Mental health issues</li>
              <li>Negative body image</li>
            </ul>
            <a href="{% url 'main:content_moderation_guidelines' %}"
               target="_blank">
              <button class="btn btn-outline-primary coc-btn float-end">Read more</button>
            </a>
          </div>
        </div>
      </div>
      <div class="card">
        <div class="card-header" id="headingThree">
          <h5 class="mb-0">
            <button aria-controls="collapseThree" aria-expanded="false" class="btn btn-link collapsed"
                    data-bs-target="#collapseThree" data-bs-toggle="collapse">
              Unacceptable stories/topics
            </button>
          </h5>
        </div>
        <div aria-labelledby="headingThree" class="collapse" data-bs-parent="#accordion" id="collapseThree">
          <div class="card-body">
            <p>
              To keep our community safe, our moderators will not make stories that include personal identifiable 
              information and/or discriminatory content publicly available.
            </p>

            Unacceptable personal details include:
            <ul>
              <li>Names of people (for example, friends, co-workers or family members)</li>
              <li>Names of workplaces, schools etc</li>
              <li>Addresses</li>
              <li>Emails</li>
              <li>Phone numbers</li>
            </ul>

            Any story that discriminates against or belittles anyone based on the following 
            characteristics will not be approved by moderators, so will not be visible to other site users:
            <ul>
              <li>Neurodivergence</li>
              <li>Gender identity and/or expression</li>
              <li>Sexual orientation</li>
              <li>Disability and/or health</li>
              <li>Physical appearance (such as skin colour, body size, etc)</li>
              <li>Nationality, citizenship, ethnic, or social origin</li>
              <li>Religion/belief (or lack thereof)</li>
              <li>Pregnancy and/or familial status</li>
              <li>Veteran status</li>
              <li>Genetic information</li>
              <li>Property and/or socio-economic status</li>
              <li>Technical preferences</li>
              <li>Experience and/or education level</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="container story-section">
  {% if uuid %}
    {% if readonly %}
      <form action="" class="form-context" method="get">
    {% else %}
        {% if show_moderation_status %}
          <form action="{% url 'main:moderate_exp' uuid %}" class="form-context" method="post">
        {% else %}
          <form action="{% url 'main:edit_exp' uuid %}" class="form-context" method="post">
        {% endif %}
    {% endif %}
  {% else %}
    <form action="{% url 'main:share_exp' %}" class="form-context" method="post">
  {% endif %}
    {% csrf_token %}
    {% regroup form by field.group as field_groups %}

    {% for group in field_groups %}
      {% if group.grouper == "hidden" %}
        {% if show_moderation_status %}
          {% for field in group.list %}
          <div class="form-group">
            <h3><label for="{{ field.id_for_label }}">{{ field.label }}</label></h3>
            {{ field }}
           </div>
           {% endfor %}
        {% endif %}
      {% elif group.grouper == 1 %}

        {% for field in group.list %}
        <div class="form-group">
          <h3><label for="{{ field.id_for_label }}">{{ field.label }}</label></h3>
          <h5>{{ field.help_text }}</h5>
          {{ field }}
        </div>
        {% endfor %}

      {% else %}
        {% if group.grouper == 2 %}
          {% define "Sensitive topics" as header %}
          {% define "Please indicate if your experience covers a sensitive topic by selecting from the following trigger labels:" as subheader %}
          {% define "col-lg-6" as columns %}
        {% endif %}
        {% if group.grouper == 3 %}
          {% define "Sharing options" as header %}
          {% define "Please indicate if you want to share your experience" as subheader %}
          {% define "col-lg-6" as columns %}
        {% endif %}
        {% if group.grouper == 4 %}
          {% define "Authorship description" as header %}
          {% define "Are you writing this experience on behalf of yourself?" as subheader %}
          {% define "col-lg-12" as columns %}
        {% endif %} 
        <div class="form-group">
          <h3><label>{{ header }}</label></h3>

          <h5>{{ subheader }}</h5>

          <div class="row">
          {% for field in group.list %}
          

            <div class="form-check {{ columns }}">
              {% if field.label == "Other"%}
                {% if readonly %}
                <input type="checkbox" name="other_trigger" id="id_other_trigger" disabled>
                {% else %}
                <input type="checkbox" name="other_trigger" id="id_other_trigger">
                {% endif %}                
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{field}}
              {% elif field.label == "First hand authorship" %}
              <label for="{{ field.id_for_label }}"></label>
                {{ field }}
              {% elif field.label == "Relationship"%}
                <label for="{{ field.id_for_label}}">{{ field.label }}:</label>
                {{ field }}
              {% else %}
                {{ field }}
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
              {% endif %}
              {% if field.help_text %}
               <div id="help_{{field.auto_id}}" class="form-text form-text-color">
                 {{field.help_text|safe}}</div>
              {% endif %}
            </div>

          {% endfor %}
          {% if group.grouper == 3 %}
          <div class="form-text form-text-color">
            If neither of these boxes is checked, only you will be able to see your story. 
            It will not be used for research and not moderated. You can change these settings at any time on the 
            <a href="{% url 'main:my_stories' %}">My stories</a> page.
          </div>
          {% endif %}
         </div>
        </div>

      {% endif %}
    {% endfor %}

    {% if change_reply %}
        <div class="form-group">
          <h3><label>Response from moderators</h3>
          <h5>Reasons provided by the moderation for their decision are listed below.</h5>

          <div id="reason-titles">
            <div class="d-flex flex-row">
              <div class="p-2 col col-lg-8 text"><b>Relevant text</b></div>
              <div class="p-2 col col-lg-4 reason"><b>Reason</b></div>
            </div>
          </div>
      {% for obj in change_reply %}
          <div id="reasons">
            <div class="d-flex flex-row mb-3 reason-row">
              <div class="p-2 col col-lg-8 border text">{{ obj.text }}</div>
              <div class="p-2 col col-lg-4 border reason"><a href="/main/content_moderation_guidelines/#{{ obj.href }}">{{ obj.reason }}</a></div>
            </div>
          </div>
      {% endfor %}
          <p>
          Time of reply: {{ changed_at|naturaltime }}
          </p>
        </div>
    {% endif %}

    {% if readonly %}
      </form>
      <div class="form-group">
        <a href="{% url 'main:edit_exp' uuid %}">
          <button class="btn btn-primary btn-lg float-end">Edit</button>
        </a>
      </div>
    {% else %}
        <div class='form-group'>
          <!-- Add an id and data attributes to the submit button -->
            <button type="button" class="btn btn-primary btn-lg float-end" id="submitBtn"
            data-uuid="{{ uuid }}" data-moderation-status="{{ moderation_status }}">Submit</button>
        </div>
      </form>
    </div>
    {% endif %}
  </section>

  <!-- Modal for the submit button -->
  <div class="modal fade" id="submitModal" tabindex="-1" role="dialog" aria-labelledby="submitModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="submitModalLabel">Confirmation</h5>
        </div>
        <div class="modal-body">
          Submitting your edited story will send it for moderation again. Do you want to proceed?
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
          <button type="button" class="btn btn-primary" id="submitForm">Submit</button>
        </div>
      </div>
    </div>
  </div>

  <script src="{% static 'js/submit-warning.js' %}"></script>
  <script src="{% static 'js/set_relationship_vis.js' %}"></script>
  </div>
{% endblock %}